apps/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.job_list, name='index'),
    path('job_detail/<int:job_id>/', views.job_detail, name='job_detail'),
    path('resume/add/', views.ResumeCreateView.as_view(), name='resume_add'),
    path('resume/<int:pk>/', views.ResumeDetailView.as_view(), name='resume_detail'),
]

job_cms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.jobs.urls', namespace='jobs')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/templates/base.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>

</head>
<body>
<h1 style="margin: auto;width: 50%">子午科技开放职位</h1>

{% block header %}
    <a href="/" style="text-decoration: none; color:#007bff">首页</a>
    <a href="{% url 'jobs:index' %}" style="text-decoration: none; color:#007bff">职位列表</a>

    {% if user.is_authenticated %}
        <a href="/accounts/logout" style="text-decoration: none; color:#007bff">退出</a>
    {% else %}
        <a href="/accounts/login" style="text-decoration: none; color:#007bff">登录</a>
    {% endif %}

    {% if user.is_authenticated %}
        <p>欢迎您！{{ user.username }}</p>
    {% else %}
        <br>欢迎您！期待您的加入，登录可以提交简历。<br>
    {% endif %}
{% endblock %}

{% block content %}

{% endblock %}
</body>
</html>

front/templates/index.html
{% extends 'base.html' %}
{% block title %}
    职位详情
{% endblock %}

{% block content %}

    {% if jobs %}
        <ul>
            {% for job in jobs %}
                <li>{{ job.type_name }} <a href="{% url 'jobs:job_detail' job_id=job.id %}"
                                           style="color:blue">{{ job.job_name }}</a> {{ job.city_name }}  </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No jobs are available.</p>
    {% endif %}

{% endblock %}

front/templates/job_detail.html
{% extends 'base.html' %}

{% block content %}

    <div style="margin:auto; width:50%;">

    {% if job %}
        <div class="position_name">
            <h2>岗位名称：{{ job.job_name }} </h2>

            城市：
            {{ job.job_city }} <p></p>
        </div>
        <hr>
        <div class="position_responsibility" style="width:600px;">
            <h3>岗位职责：</h3>
            <pre style="font-size:16px">{{ job.job_duty }}
        </pre>
        </div>

        <hr>
        <div class="position_requirement" style="width:600px; ">
            <h3>任职要求：</h3>
            <pre style="font-size:16px">{{ job.job_require }}
        </pre>
        </div>

        <div class="apply_position">
            <input type="button" class="btn btn-primary" style="width:120px;" value="申请"
                   onclick="location.href='/resume/add/?apply_position={{ job.job_name }}&city={{ job.job_city }}'"/>
        </div>
    {% else %}
        <p>职位不存在</p>
    {% endif %}

{% endblock %}
</div>

front/templates/resume_detail.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<h1>简历详细信息 </h1>

<div> 姓名: {{ object.username }} </div> <div>城市： {{ object.city }}</div> <div>手机号码: {{ object.phone }}</div>

<p></p>
<div>邮件地址: {{ object.email}}</div>
<div>申请职位: {{ object.apply_position}}</div>
<div>出生地: {{ object.born_address}}</div>
<div>性别: {{ object.gender}}</div>
<hr>

<div>本科学校: {{ object.bachelor_school}}</div>
<div>研究所学校: {{ object.master_school}}</div>
<div>专业: {{ object.major}}</div>
<div>学历: {{ object.degree}}</div>
<hr>

<p>候选人介绍: {{ object.candidate_introduction}}</p>
<p>工作经历: {{ object.work_experience}}</p>
<p>项目经历: {{ object.project_experience}}</p>

front/templates/resume_form.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<a href="/" style="text-decoration: none; color:#007bff">首页</a>
<a href="{% url 'jobs:index' %}" style="text-decoration: none; color:#007bff">职位列表</a>


<form method="post" method="post" class="form" enctype="multipart/form-data" style="width:600px;margin-left:5px">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button type="submit" class="btn btn-primary">
            提交
        </button>
    {% endbuttons %}
</form>